BIN1 = tst-cancelx16
BIN1.SRC = tst-cancelx16.c

BIN2 = tst-cancelx16-sleep
BIN2.SRC = tst-cancelx16-sleep.c

FLAGS = -fexceptions
WARN_EXTRA = -Werror

# make CROSS_COMPILE=or1k-smh-linux-gnu-
CROSS_COMPILE ?=

OPTIONS = pthread

# Make file from Richard Bradley https://github.com/hirdrac/makefile
include Makefile.mk
