BIN1 = tst-cancel7
BIN1.SRC = tst-cancel7.c

WARN_EXTRA = -Werror

# make CROSS_COMPILE=or1k-smh-linux-gnu-
CROSS_COMPILE ?=

OPTIONS = pthread

# Make file from Richard Bradley https://github.com/hirdrac/makefile
include Makefile.mk
