BIN1 = throw
BIN1.SRC = throw.cc

BIN2 = throw-pthread
BIN2.SRC = throw-pthread.cc

BIN3 = throw-pthread-sem
BIN3.SRC = throw-pthread-sem.cc

WARN_EXTRA = -Werror

# make CROSS_COMPILE=or1k-smh-linux-gnu-
CROSS_COMPILE ?=

OPTIONS = pthread

# Make file from Richard Bradley https://github.com/hirdrac/makefile
include Makefile.mk
