BIN1 = ptrace-sleep
BIN1.SRC = ptrace-sleep.c

WARN_EXTRA = -Werror

# make CROSS_COMPILE=or1k-smh-linux-gnu-
CROSS_COMPILE ?=

# Make file from Richard Bradley https://github.com/hirdrac/makefile
include Makefile.mk
